export const ANIMAL_ACTIONS_TYPE = {
  SET_ANIMALS_DATA: 'SET_ANIMALS_DATA',
  SET_SELECTED_ANIMAL: 'SET_SELECTED_ANIMAL',
  SET_FILTERED_ANIMALS: 'SET_FILTERED_ANIMALS',
  SET_PREGNANT_ANIMALS: 'SET_PREGNANT_ANIMALS',
  SET_SEARCH_ANIMALS: 'SET_SEARCH_ANIMALS',
};
